version: "3.7"
services:
  controller:
    build: .
    restart: always

    ports:
      - "8181:8181"
    environment:
      - SPECTATOR_CHANNEL=spectator_twitch_channel
      - CHATBOT_USERNAME=chatbot_username
      - CHATBOT_OAUTH_ACCESS_TOKEN=chatbot_oauth_token
      - SPECTATOR_NAME=spectator_account_name
